### PR TITLE
add campaign feature

### PR DESCRIPTION
**Pull request by anjolabassey**

### CODE REVIEW

**Comment by iamraphson** [comment]
@anjolabassey kindly provide a link to the docs

**Comment by temiadesina** [comment]
> @anjolabassey kindly provide a link to the docs

Hey @iamraphson the campaign ID feature is only available on Request, it is a discount feature on Rave open to select Merchants. So it's not on the documentation

**Comment by iamraphson** [comment]
@temiadesina so I should merge it??

**Comment by temiadesina** [comment]
> @temiadesina so I should merge it??

Yes please @iamraphson

**Review by iamraphson — APPROVED** [review]

**Pull request merged**
